services:
  kizuna:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - kizuna-data:/data
    environment:
      CONFIG_PATH: /data/config.json

  kizuna-debug:
    build:
      context: .
      target: debug
    profiles:
      - debug
    ports:
      - "9091:9090"
      - "2345:2345"
    volumes:
      - kizuna-data:/data
    environment:
      CONFIG_PATH: /data/config.json
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE

volumes:
  kizuna-data:
    name: kizuna-data
